### ISSUE TITLE
Off and back On with Toggle switch help.

### ISSUE THREAD

**Issue by D-an-W** [TonyLHansen/raspberry-pi-safe-off-switch#13]
Hi @TonyLHansen, using one of your scripts I was able to turn off my Pi 5 in an Arcade cabinet using a toggle switch across pins 5 and 6 but as yet I cannot figure out how to turn it back ok using the same switch (In the opposite direction).

Would you know if this is even possible please?

I realise the Pi 5 now has a power button but as I am moving from a Pi 4 all the hardware is already in place and I was hoping to be able to migrate from the working RPi.GPIO to gpiozero but so far not got it working.

Many thanks.

**Comment by TonyLHansen** [comment]
An on switch is also known as a reset switch. For an on switch, you need to connect a switch across the Run pins on the Raspberry Pi board. Shorting those pins will cause the Raspberry Pi to enter a controlled reboot. However, when I say pins, you have to realize that the boards only have holes for a pair of pins to be soldered. Where those pins are has varied vastly between versions of the Raspberry Pi. On some Raspberry Pis, the holes are labeled Run. On some, they are labeled P6. On the Raspberry Pi 4, there are three pins next to each other: Run, unlabeled, and GLOBAL_EN -- solder your pin into the Run and the unlabeled holes.

You have two choices: use two separate switches, or use a single momentary double pole double throw toggle switch. With the DPDT switch, connect one side as the off switch, and connect the other side as a reset switch.

Be very careful though: unless you are very careful with setting up a hardened Pi with read-only filesystems, you do NOT want to hit the reset when you have a running system. Accidentally hitting reset while the Pi is running can lead to SD card corruption. So that is one argument for having separate switches, and/or possibly using a switch guard of some sort over or next to the reset switch. For example, with a DPDT switch, you could have a spring-loaded item you have to push down or to the side before you can push the DPDT switch to the reset position. Think of the movies of pilots having to flip up a safety guard before a button can be pushed; I think that would look cool on an arcade cabinet.

Good luck! I'd be interested in hearing what you come up with.

**Comment by D-an-W** [comment]
Thanks @TonyLHansen, with the Pi 4 I have been using the script below with great success but I can't seem to get RPi.GPIO to work on the Pi 5 running RetroPie on Bookworm (Lite)...

https://github.com/dmanlfc/arcade1up/blob/master/Raspberry%20Pi/shutdown.py

I was hoping to be able to achieve this on the Pi 5 without any hardware changes but not had any luck so far.

**Comment by TonyLHansen** [comment]
An on switch is also known as a reset switch. For an on switch, you need to connect a switch across the Run pins on the Raspberry Pi board. Shorting those pins will cause the Raspberry Pi to enter a controlled reboot. However, when I say pins, you have to realize that the boards only have holes for a pair of pins to be soldered. Where those pins are has varied vastly between versions of the Raspberry Pi. On some Raspberry Pis, the holes are labeled Run. On some, they are labeled P6. On the Raspberry Pi 4, there are three pins next to each other: Run, unlabeled, and GLOBAL_EN -- solder your pin into the Run and the unlabeled holes.

You have two choices: use two separate switches, or use a single momentary double pole double throw toggle switch. With the DPDT switch, connect one side as the off switch, and connect the other side as a reset switch.

Be very careful though: unless you are very careful with setting up a hardened Pi with read-only filesystems, you do NOT want to hit the reset when you have a running system. Accidentally hitting reset while the Pi is running can lead to SD card corruption. So that is one argument for having separate switches, and/or possibly using a switch guard of some sort over or next to the reset switch. For example, with a DPDT switch, you could have a spring-loaded item you have to push down or to the side before you can push the DPDT switch to the reset position. Think of the movies of pilots having to flip up a safety guard before a button can be pushed; I think that would look cool on an arcade cabinet.

Good luck! I'd be interested in hearing what you come up with.

**Comment by TonyLHansen** [comment]
I realized I misread your original question. I haven't yet gotten a Raspberry Pi 5 board, so can't verify anything.

RPi.GPIO is a third-party library and might not have been upgraded to support the Pi5. Try using one of the shutdown scripts from this repo instead, which all use gpiozero. For example, shutdown-press-simple.py or shutdown-with-hold.py.

I looked at pictures of the Raspberry Pi 5, and do NOT see Run holes onto which you can add your own reset switch. (There are a pair of holes below the battery connector that are unlabeled, but I can't verify yet what they are connected to.) I also do NOT see an easy way to extend the on-board switch -- there's no solder holes next to that either.

**Comment by TonyLHansen** [comment]
@D-an-W, I found the info you need. The page <[raspberry-pi-5.html](https://www.raspberrypi.com/documentation/computers/raspberry-pi-5.html)> describes the J2 holes, which are indeed the unlabeled pair of holes below the battery connector. According to that page, 

> The J2 jumper, located between the RTC battery connector and the board edge, is a breakout allowing you to add your own power button to Raspberry Pi 5 by adding a Normally Open (NO) momentary switch bridging the two pads. Briefly closing this switch will perform the same actions as the onboard power button.
